"""kibitz extensions

Revision ID: 17e145179a5b
Revises: 1f84adc3c494
Create Date: 2024-04-05 13:24:15.205967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17e145179a5b"
down_revision: Union[str, None] = "1f84adc3c494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kibitz",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("game", sa.Integer(), nullable=True),
        sa.Column("role", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game"], ["games.id"], name="fk_kibitz_games_id_game", onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("fk_participants_games_id_game", "participants", type_="foreignkey")
    op.create_foreign_key(
        "fk_participants_games_id_game",
        "participants",
        "games",
        ["game"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_participants_games_id_game", "participants", type_="foreignkey")
    op.create_foreign_key("fk_participants_games_id_game", "participants", "games", ["game"], ["id"])
    op.drop_table("kibitz")
    # ### end Alembic commands ###
