"""game models

Revision ID: 1f84adc3c494
Revises: 8b828974262c
Create Date: 2024-04-05 09:50:35.491736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f84adc3c494'
down_revision: Union[str, None] = '8b828974262c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.BigInteger(), nullable=False),
    sa.Column('player_role', sa.BigInteger(), nullable=False),
    sa.Column('st_role', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_games',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_active_games_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('member', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('PLAYER', 'STORYTELLER', 'NONE', name='roletype'), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_participants_games_id_game'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_threads_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('fk_documents_scripts_id_script', 'documents', type_='foreignkey')
    op.create_foreign_key('fk_documents_scripts_id_script', 'documents', 'scripts', ['script'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_scripts_id_script', 'documents', type_='foreignkey')
    op.create_foreign_key('fk_documents_scripts_id_script', 'documents', 'scripts', ['script'], ['id'])
    op.drop_table('threads')
    op.drop_table('participants')
    op.drop_table('active_games')
    op.drop_table('games')
    op.drop_table('categories')
    # ### end Alembic commands ###
