"""feedback metrics and comment types

Revision ID: 58562efa9e2d
Revises: 8d1198bb424a
Create Date: 2024-04-07 14:35:23.191460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58562efa9e2d'
down_revision: Union[str, None] = '8d1198bb424a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('storyteller', sa.BigInteger(), nullable=False),
    sa.Column('submitter', sa.BigInteger(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('enjoyability', sa.Integer(), nullable=False),
    sa.Column('organization', sa.Integer(), nullable=False),
    sa.Column('pacing', sa.Integer(), nullable=False),
    sa.Column('attentiveness', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=600), nullable=True),
    sa.Column('comments', sa.String(length=600), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_feedback_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
