"""fix(*): hard reset due to constraint issues

Revision ID: 7d4746d006f0
Revises: 
Create Date: 2024-04-08 09:03:09.608163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4746d006f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.BigInteger(), nullable=False),
    sa.Column('player_role', sa.BigInteger(), nullable=False),
    sa.Column('st_role', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('author', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('author', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_games',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_active_games_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctype', sa.String(length=10), nullable=False),
    sa.Column('script', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['script'], ['scripts.id'], name='fk_documents_scripts_id_script', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('storyteller', sa.BigInteger(), nullable=False),
    sa.Column('submitter', sa.BigInteger(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('enjoyability', sa.Integer(), nullable=False),
    sa.Column('organization', sa.Integer(), nullable=False),
    sa.Column('pacing', sa.Integer(), nullable=False),
    sa.Column('attentiveness', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=600), nullable=True),
    sa.Column('comments', sa.String(length=600), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_feedback_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('reminder', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_game_reminders_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder'], ['reminders.id'], name='fk_game_reminders_reminders_id_reminder', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder')
    )
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reminder'], ['reminders.id'], name='fk_intervals_reminders_id_reminder', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kibitz',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_kibitz_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('member', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('PLAYER', 'STORYTELLER', 'NONE', name='roletype'), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_participants_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('member', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_signups_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_threads_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threads')
    op.drop_table('signups')
    op.drop_table('participants')
    op.drop_table('kibitz')
    op.drop_table('intervals')
    op.drop_table('game_reminders')
    op.drop_table('feedback')
    op.drop_table('documents')
    op.drop_table('active_games')
    op.drop_table('scripts')
    op.drop_table('reminders')
    op.drop_table('games')
    op.drop_table('categories')
    op.drop_table('archive_categories')
    # ### end Alembic commands ###
