"""bigint for author snowflake

Revision ID: 8b828974262c
Revises: 
Create Date: 2024-04-03 10:35:03.234026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b828974262c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scripts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("author", sa.BigInteger(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("logo", sa.String(length=500), nullable=True),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doctype", sa.String(length=10), nullable=False),
        sa.Column("script", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["script"], ["scripts.id"], name="fk_documents_scripts_id_script"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    op.drop_table("scripts")
    # ### end Alembic commands ###
