"""signups distinct from participants

Revision ID: e6fd78f3042a
Revises: 831835a9ad34
Create Date: 2024-04-06 10:31:38.122207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fd78f3042a'
down_revision: Union[str, None] = '831835a9ad34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('member', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name='fk_signups_games_id_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signups')
    # ### end Alembic commands ###
